services:
  postgres:
    container_name: gym_pass
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=gym-pass
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
    name: gym_pass_data
